# Generated by Django 3.2.15 on 2022-09-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cate',
            new_name='category',
        ),
    ]
